# a matrix list of variables used in the container build process
include:
  - from_image_name: "docker.io/library/python"
    from_image_tag: "3.9-slim"
    image_name: "python-base"
    image_tags: "3.9-slim, 3.9"
  - from_image_name: "docker.io/library/python"
    from_image_tag: "3.10-slim"
    image_name: "python-base"
    image_tags: "3.10-slim, 3.10"
  - from_image_name: "docker.io/library/python"
    from_image_tag: "3.11-slim"
    image_name: "python-base"
    image_tags: "3.11-slim, 3.11"
