# a matrix list of variables used in the container build process
include:
  - from_image_name: "docker.io/library/python"
    from_image_tag: "3.9-slim"
    image_name: "python-base"
    image_tag: "3.9-slim"
  - from_image_name: "docker.io/library/python"
    from_image_tag: "3.10-slim"
    image_name: "python-base"
    image_tag: "3.10-slim"
  - from_image_name: "docker.io/library/python"
    from_image_tag: "3.11-slim"
    image_name: "python-base"
    image_tag: "3.11-slim"
