# a matrix list of variables used in the container build process
include:
  - BASE_IMAGE_TAG: "3.10-slim"
    BUILD_IMAGE_NAME: "python-base"
    BUILD_IMAGE_TAGS: "3.10-slim,3.10"
  - BASE_IMAGE_TAG: "3.11-slim"
    BUILD_IMAGE_NAME: "python-base"
    BUILD_IMAGE_TAGS: "3.11-slim,3.11"
  - BASE_IMAGE_TAG: "3.12-slim"
    BUILD_IMAGE_NAME: "python-base"
    BUILD_IMAGE_TAGS: "3.12-slim,3.12"
