# https://taskfile.dev
version: "3"

tasks:

  build-image:
    desc: Build docker image
    cmds:
      - >
        export `cat .env_dev` && docker build
        --build-arg HTTP_PROXY
        --build-arg HTTPS_PROXY
        --build-arg NO_PROXY
        --build-arg CI_REGISTRY
        --progress plain
        -t python-base .

  test-image:
    desc: Test docker image
    cmds:
      - task: build-image
      - docker run --rm -it python-base bash -c "python --version"

