include:
  - local: "/.gitlab/.build.env.yml"
  - project: '$GITLAB_CI_PATH'
    ref: '$GITLAB_CI_REF_NAME'
    file: '/ext/.build_docker_image.yml'

.rules:
  build_image:
    - if: $CI_COMMIT_TAG
    - if: $CI_MATRIX_BUILD==null && ($CI_PIPELINE_SOURCE == "web" || $CI_PIPELINE_SOURCE == "api")

variables:
  DOCKER_BUILD_ARGS: >-
    --build-arg BASE_IMAGE_NAME --build-arg BASE_IMAGE_TAG
  CACHE_IMAGE: $CI_REGISTRY/$CI_REGISTRY_PATH/$BUILD_IMAGE_NAME:buildcache_$BUILD_IMAGE_TAG

###### VALIDATE ######
# validate_dockerfile:
#   stage: validate
#   extends:
#     - .validate_dockerfile

# validate_shell:
#   stage: validate
#   extends:
#     - .validate_shell


###### BUILD IMAGE ######
trigger_build_image:
  stage: build
  rules: !reference [.rules, build_image]
  variables:
    PARENT_PIPELINE_ID: $CI_PIPELINE_ID
  trigger:
    include:
      - local: '/.gitlab/workflows/build-image.yml'
    strategy: depend


