include:
  - project: '$GITLAB_CI_PATH'
    ref: '$GITLAB_CI_REF_NAME'
    file: '/ext/.build_docker_image.yml'

variables:
  DOCKER_BUILD_ARGS: >-
    --build-arg BASE_IMAGE_NAME --build-arg BASE_IMAGE_TAG

.rules:
  build_image_rules:
    - if: $CI_COMMIT_TAG
    - if: $CI_PIPELINE_SOURCE == "web" || $CI_PIPELINE_SOURCE == "api"
    - if: $CI_OPTIMIZE_PIPELINE == "true"
      changes:
        - Dockerfile
    - if: $CI_OPTIMIZE_PIPELINE == "false"
  release_branch_rules:
    - if: $CI_COMMIT_TAG
      when: never
    - if: $CI_PIPELINE_SOURCE == "web" || $CI_PIPELINE_SOURCE == "api"
    - if: $CI_OPTIMIZE_PIPELINE == "true"
      changes:
        - Dockerfile
    - if: $CI_OPTIMIZE_PIPELINE == "false"


build_image:
  extends:
    - .build_image
  stage: build
  rules: !reference [.rules, build_image_rules]



