include:
  - project: '$GITLAB_CI_PATH'
    ref: '$GITLAB_CI_REF_NAME'
    file: '/ext/.build_docker_image.yml'

variables:
  PYTHON_VERSION: "3.9"

.rules:
  build_image_rules:
    - if: $CI_COMMIT_TAG
    - if: $CI_PIPELINE_SOURCE == "web" || $CI_PIPELINE_SOURCE == "api"
    - if: $CI_OPTIMIZE_PIPELINE == "true"
      changes:
        - Dockerfile
    - if: $CI_OPTIMIZE_PIPELINE == "false"
  release_branch_rules:
    - if: $CI_COMMIT_TAG
      when: never
    - if: $CI_PIPELINE_SOURCE == "web" || $CI_PIPELINE_SOURCE == "api"
    - if: $CI_OPTIMIZE_PIPELINE == "true"
      changes:
        - Dockerfile
    - if: $CI_OPTIMIZE_PIPELINE == "false"


build_image:
  extends:
    - .build_image
  stage: build
  script:
    - >-
      docker build
      --build-arg HTTP_PROXY
      --build-arg HTTPS_PROXY
      --build-arg NO_PROXY
      --build-arg CI_REGISTRY=$CI_REGISTRY/$CI_REGISTRY_PATH
      --cache-from $BRANCH_IMAGE
      --progress plain -t $BUILD_IMAGE .
    - docker push $BUILD_IMAGE
  rules: !reference [.rules, build_image_rules]



