# These variables are used to build image and can be overridden in the CI/CD settings.
variables:
  REQUESTS_CA_BUNDLE: /etc/ssl/certs/ca-certificates.crt
  CI_MATRIX_BUILD:
    description: "Run matrix build. If set to `true`, the build will run in parallel for each Python version from `.matrix.yml`."
    value: "false"
    options:
      - "true"
      - "false"
  BASE_IMAGE_NAME: docker.io/library/python
  BASE_IMAGE_TAG:
    description: "Base image tag to use for the build (e.g., 3.12.2-slim)"
    value: "3.10-slim"
  BUILD_IMAGE_NAME: python-base
  BUILD_IMAGE_TAG:
    description: "Image tag to use for the build (e.g., 3.12.2-slim)"
    value: "3.10-slim"
  BUILD_IMAGE_TAGS:
    description: "Comma-separated list of tags to apply to the image (e.g., 3.12.2-slim, latest)"
    value: "3.10"
  PLATFORMS: linux/amd64,linux/arm64
