# These variables are used to build image and can be overridden in the CI/CD settings.
variables:
  REQUESTS_CA_BUNDLE: /etc/ssl/certs/ca-certificates.crt
  BASE_IMAGE_NAME: docker.io/library/python
  BASE_IMAGE_TAG: 3.10-slim
  BUILD_IMAGE_NAME: python-base
  BUILD_IMAGE_TAG: 3.10-slim
  BUILD_IMAGE_TAGS: "3.10"
  PLATFORMS: linux/amd64,linux/arm64