name: build_image
description: Build and push Docker image to Docker Hub

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  build_image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
      - run: docker version

      - name: Set dynamic variable
        run: |
          export `cat .build.env` && \
          ref_name=$(git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/HEAD detached at //' -e 's/* (\(.*\))/\1/' -e 's/* \(.*\)/\1/');
          if [[ "$ref_name" == 3* ]]; then
            PYTHON_BASE_IMAGE_TAG=$ref_name;
          else
            PYTHON_BASE_IMAGE_TAG=$PYTHON_BASE_IMAGE_TAG_DEFAULT;
          fi
          echo "PYTHON_BASE_IMAGE_TAG=$PYTHON_BASE_IMAGE_TAG" >> $GITHUB_ENV
          PYTHON_VERSION=$(echo $PYTHON_BASE_IMAGE_TAG | cut -d'-' -f1 | awk 'NR==1{split($1, a, "."); print a[1]"."a[2]}')
          echo "PYTHON_VERSION=$PYTHON_VERSION" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          echo "Build from base image with tag=$PYTHON_BASE_IMAGE_TAG"
          export `cat .build.env` && \
          docker build \
          --build-arg PYTHON_BASE_IMAGE_TAG=$PYTHON_BASE_IMAGE_TAG \
          --progress plain \
          -t ghcr.io/${{ github.repository_owner }}/python-base:${PYTHON_BASE_IMAGE_TAG} .

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/python-base:${PYTHON_BASE_IMAGE_TAG}

