name: Image Build
description: Build and push Docker image to GitHub Container Registry

on:
  push:
    tags:
      - '*'
  workflow_dispatch:
    inputs:
      from_image_tag:
        description: "Base image tag to use for the build (e.g., 3.12.2-slim)"
        required: false
      image_tag:
        description: "Image tag to use for the build (e.g., 3.12)"
        required: false

concurrency:
  group: "${{ github.repository_id }}"

jobs:
  setup_build_env:
    name: Setup build environment
    runs-on: ubuntu-latest

    outputs:
      from_image_name: ${{ steps.setup.outputs.FROM_IMAGE_NAME }}
      from_image_tag: ${{ steps.setup.outputs.FROM_IMAGE_TAG }}
      image_name: ${{ steps.setup.outputs.IMAGE_NAME }}
      image_tag: ${{ steps.setup.outputs.IMAGE_TAG }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup build environment
        id: setup
        run: |

          # Check if the base image tag is provided from workflow_dispatch user's input
          FROM_IMAGE_TAG=$(if [ -n "${{ inputs.from_image_tag }}" ]; then echo ${{ inputs.from_image_tag }}; else echo $(./scripts/bash_helpers.sh get_image_tag); fi)
          echo "FROM_IMAGE_TAG=$FROM_IMAGE_TAG" >> $GITHUB_OUTPUT

          # Check if the image tag is provided from workflow_dispatch user's input
          IMAGE_TAG=$(if [ -n "${{ inputs.image_tag }}" ]; then echo ${{ inputs.image_tag }}; else echo $FROM_IMAGE_TAG; fi)
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_OUTPUT

          # This file 'build.env' should contain the environment variables used in the Dockerfile and the build process.
          set -a; source .github/.build.env; set +a;
          echo "FROM_IMAGE_NAME=$FROM_IMAGE_NAME" >> $GITHUB_OUTPUT
          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_OUTPUT


  build:
    name: 'Build ${{ needs.setup_build_env.outputs.image_name }}:${{ needs.setup_build_env.outputs.image_tag }}'
    permissions:
      contents: read
      packages: write
    needs: setup_build_env
    uses: alexchay/github-ci/.github/workflows/build_and_push_image_to_ghcr.yml@main
    with:
      from_image_name: ${{ needs.setup_build_env.outputs.from_image_name }}
      from_image_tag: ${{ needs.setup_build_env.outputs.from_image_tag }}
      image_name: ${{ needs.setup_build_env.outputs.image_name }}
      image_tag: ${{ needs.setup_build_env.outputs.image_tag }}
