name: build_image
description: Build and push Docker image to Docker Hub

on:
  workflow_dispatch:

jobs:
  build_image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
      - run: docker version

      - name: Set dynamic variable
        run: |
          echo "PYTHON_BASE_IMAGE_TAG=$(git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/HEAD detached at //' -e 's/* (\(.*\))/\1/' -e 's/* \(.*\)/\1/')" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          echo "Build from base image with tag=$PYTHON_BASE_IMAGE_TAG"
          export `cat .build.env` && \
          docker build \
          --build-arg PYTHON_BASE_IMAGE_TAG=$PYTHON_BASE_IMAGE_TAG \
          --progress plain \
          -t ghcr.io/${{ github.repository }}:${PYTHON_BASE_IMAGE_TAG} .

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository }}:${PYTHON_BASE_IMAGE_TAG}

