name: Dockerfile

on:
  workflow_dispatch:
  push:
    paths:
      - Dockerfile
  pull_request:
    paths:
      - Dockerfile

jobs:
  validate-dockerfile:
    name: Dockerfile validation
    uses: alexchay/github-ci/.github/workflows/validate_dockerfile.yml@main
