name: Validate shell scripts

on:
  workflow_dispatch:
  push:
    paths:
      - scripts/**/*.sh
  pull_request:
    paths:
      - scripts/**/*.sh

jobs:
  validate:
    name: Validate shell scripts
    uses: alexchay/github-ci/.github/workflows/validate_shellscripts.yml@main
