name: Validate Dockerfile

on:
  workflow_dispatch:
  push:
    paths:
      - Dockerfile
  pull_request:
    paths:
      - Dockerfile

jobs:
  validate:
    name: Validate Dockerfile
    uses: alexchay/github-ci/.github/workflows/validate_dockerfile.yml@main
